media:
  input: assets
  output: /assets
content:
  - name: pages
    label: Pages du site
    type: file
    file: index.html
    fields:
      - name: body
        label: Contenu du site
        type: rich-text