media:
  input: assets
  output: /assets
content:
  - name: homepage
    label: Page d'accueil
    type: file
    file: index.html
    fields:
      - name: body
        label: Contenu du site
        type: rich-text
