backend:
  name: git-gateway
  branch: main

media_folder: images

collections:
  - name: pages
    label: Pages
    files:
      - file: index.html
        label: Page d'Accueil
        name: index
        fields:
          - { label: "Titre principal", name: title, widget: string }
          - { label: "Numéro de Téléphone", name: phone, widget: string }
          - { label: "Adresse E-mail", name: email, widget: string }
          - { label: "Texte Présentation", name: description, widget: text }
